default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_shop_development
  host: db
  username: <%= ENV.fetch("DB_USER") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") {} %>

test:
  <<: *default
  database: demo_shop_test

production:
  <<: *default
  database: demo_shop_production
  username: demo_shop
  password: <%= ENV["DEMO_SHOP_DATABASE_PASSWORD"] %>
